// src/app/teacher/students/page.tsx
'use client';

import { useState } from 'react';
import useSWR from 'swr';

const fetcher = (url: string) => fetch(url).then((res) => res.json());

export default function StudentsPage() {
  const { data: response, isLoading, mutate } = useSWR('/api/students', fetcher);
  const students = response?.data || [];

  const [isAdding, setIsAdding] = useState(false);
  const [formData, setFormData] = useState({ username: '', password: '', displayName: '' });
  
  const [editingId, setEditingId] = useState<string | null>(null);
  const [editData, setEditData] = useState({ displayName: '', password: '', isActive: true });
  const [isDeleting, setIsDeleting] = useState(false);

  const handleAdd = async (e: React.FormEvent) => {
    e.preventDefault();
    const res = await fetch('/api/students', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(formData)
    });
    if (res.ok) {
      setIsAdding(false);
      setFormData({ username: '', password: '', displayName: '' });
      mutate();
    } else {
      const data = await res.json();
      alert(data.error || '添加失败');
    }
  };

  const handleEdit = (student: any) => {
    setEditingId(student.id);
    setEditData({ displayName: student.displayName, password: '', isActive: student.isActive ?? true });
  };

  const handleSaveEdit = async (id: string) => {
    const res = await fetch(`/api/students/${id}`, {
      method: 'PUT',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(editData)
    });
    if (res.ok) {
      setEditingId(null);
      mutate();
    } else {
      const data = await res.json();
      alert(data.error || '修改失败');
    }
  };

  const handleDelete = async (id: string) => {
    if (!confirm('警告：您即将删除该学生。这将同时硬删除其所有生图记录和历史对话！此操作不可恢复。确定要删除吗？')) return;
    setIsDeleting(true);
    try {
      const res = await fetch(`/api/students/${id}`, { method: 'DELETE' });
      if (res.ok) {
        mutate();
      } else {
        const data = await res.json();
        alert(data.error || '删除失败');
      }
    } finally {
      setIsDeleting(false);
    }
  };

  return (
    <div style={{ maxWidth: '1200px', margin: '0 auto' }}>
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '1.5rem' }}>
         <h1>学生管理</h1>
         <button className="btn btn-primary" onClick={() => setIsAdding(!isAdding)}>
            {isAdding ? '取消' : '添加学生'}
         </button>
      </div>

      {isAdding && (
         <div className="glass-panel" style={{ padding: '1.5rem', marginBottom: '2rem' }}>
            <h2 style={{ fontSize: '1.2rem', marginBottom: '1rem' }}>添加新学生</h2>
            <form onSubmit={handleAdd} style={{ display: 'flex', gap: '1rem', alignItems: 'flex-end' }}>
               <div style={{ flex: 1 }}>
                  <label style={{ display: 'block', marginBottom: '0.5rem', fontSize: '0.9rem', color: 'var(--text-muted)' }}>学号/账号</label>
                  <input required value={formData.username} onChange={e => setFormData({...formData, username: e.target.value})} style={{ width: '100%' }} />
               </div>
               <div style={{ flex: 1 }}>
                  <label style={{ display: 'block', marginBottom: '0.5rem', fontSize: '0.9rem', color: 'var(--text-muted)' }}>姓名</label>
                  <input required value={formData.displayName} onChange={e => setFormData({...formData, displayName: e.target.value})} style={{ width: '100%' }} />
               </div>
               <div style={{ flex: 1 }}>
                  <label style={{ display: 'block', marginBottom: '0.5rem', fontSize: '0.9rem', color: 'var(--text-muted)' }}>密码</label>
                  <input required type="password" value={formData.password} onChange={e => setFormData({...formData, password: e.target.value})} style={{ width: '100%' }} />
               </div>
               <button type="submit" className="btn btn-primary" style={{ height: '42px' }}>保存</button>
            </form>
         </div>
      )}

      <div className="glass-panel">
         {isLoading ? (
            <div style={{ padding: '2rem', textAlign: 'center' }}>加载中...</div>
         ) : students.length === 0 ? (
            <div style={{ padding: '2rem', textAlign: 'center', color: 'var(--text-muted)' }}>暂无学生，请先添加</div>
         ) : (
            <table style={{ width: '100%', borderCollapse: 'collapse', textAlign: 'left' }}>
               <thead>
                  <tr style={{ borderBottom: '1px solid var(--border-color)' }}>
                     <th style={{ padding: '1rem', color: 'var(--text-muted)', fontWeight: 500 }}>账号</th>
                     <th style={{ padding: '1rem', color: 'var(--text-muted)', fontWeight: 500 }}>姓名</th>
                     <th style={{ padding: '1rem', color: 'var(--text-muted)', fontWeight: 500 }}>状态</th>
                     <th style={{ padding: '1rem', color: 'var(--text-muted)', fontWeight: 500 }}>加入时间</th>
                     <th style={{ padding: '1rem', color: 'var(--text-muted)', fontWeight: 500 }}>生成次数</th>
                     <th style={{ padding: '1rem', color: 'var(--text-muted)', fontWeight: 500, textAlign: 'right' }}>操作</th>
                  </tr>
               </thead>
               <tbody>
                  {students.map((student: any) => (
                     <tr key={student.id} style={{ borderBottom: '1px solid rgba(0,0,0,0.05)', background: editingId === student.id ? 'var(--surface-cream-strong)' : 'transparent' }}>
                        <td style={{ padding: '1rem' }}>{student.username}</td>
                        <td style={{ padding: '1rem' }}>
                           {editingId === student.id ? (
                              <input 
                                 value={editData.displayName} 
                                 onChange={e => setEditData({...editData, displayName: e.target.value})} 
                                 style={{ padding: '0.4rem', width: '120px' }}
                              />
                           ) : (
                              student.displayName
                           )}
                        </td>
                        <td style={{ padding: '1rem' }}>
                           {editingId === student.id ? (
                              <select 
                                 value={editData.isActive ? 'true' : 'false'}
                                 onChange={e => setEditData({...editData, isActive: e.target.value === 'true'})}
                                 style={{ padding: '0.4rem' }}
                              >
                                 <option value="true">正常</option>
                                 <option value="false">已停用</option>
                              </select>
                           ) : (
                              <span style={{ 
                                 padding: '4px 8px', 
                                 borderRadius: '12px', 
                                 fontSize: '12px',
                                 background: student.isActive !== false ? 'rgba(34, 197, 94, 0.1)' : 'rgba(239, 68, 68, 0.1)',
                                 color: student.isActive !== false ? '#15803d' : '#b91c1c'
                              }}>
                                 {student.isActive !== false ? '正常' : '已停用'}
                              </span>
                           )}
                        </td>
                        <td style={{ padding: '1rem', color: 'var(--text-muted)' }}>{new Date(student.createdAt).toLocaleDateString()}</td>
                        <td style={{ padding: '1rem' }}>{student._count.generations}</td>
                        <td style={{ padding: '1rem', textAlign: 'right' }}>
                           {editingId === student.id ? (
                              <div style={{ display: 'flex', gap: '0.5rem', justifyContent: 'flex-end', alignItems: 'center' }}>
                                 <input 
                                    type="password" 
                                    placeholder="留空不改密码" 
                                    value={editData.password} 
                                    onChange={e => setEditData({...editData, password: e.target.value})}
                                    style={{ padding: '0.4rem', width: '120px', fontSize: '0.8rem' }}
                                 />
                                 <button className="btn btn-primary" style={{ padding: '0.4rem 0.8rem' }} onClick={() => handleSaveEdit(student.id)}>保存</button>
                                 <button className="btn btn-secondary" style={{ padding: '0.4rem 0.8rem' }} onClick={() => setEditingId(null)}>取消</button>
                              </div>
                           ) : (
                              <div style={{ display: 'flex', gap: '0.5rem', justifyContent: 'flex-end' }}>
                                 <button className="btn btn-secondary" style={{ padding: '0.4rem 0.8rem' }} onClick={() => handleEdit(student)}>编辑</button>
                                 <button className="btn btn-secondary" style={{ padding: '0.4rem 0.8rem', color: 'var(--error)' }} onClick={() => handleDelete(student.id)} disabled={isDeleting}>删除</button>
                              </div>
                           )}
                        </td>
                     </tr>
                  ))}
               </tbody>
            </table>
         )}
      </div>
    </div>
  );
}

// frontend/src/views/teacher/Students.vue
<script setup lang="ts">
import { ref, onMounted } from 'vue'
import { useAuthStore } from '../../stores/auth'

const authStore = useAuthStore()

interface Student {
  id: string
  username: string
  displayName: string
  isActive: boolean
  tokenQuota: number
  createdAt: string
  _count?: { generations: number }
}

const students = ref<Student[]>([])
const loading = ref(false)

const isAdding = ref(false)
const formData = ref({ username: '', password: '', displayName: '' })

const editingId = ref<string | null>(null)
const editData = ref({ displayName: '', password: '', isActive: true })
const isDeleting = ref(false)
const fileInput = ref<HTMLInputElement | null>(null)

const fetchStudents = async () => {
  loading.value = true
  try {
    const res = await fetch('http://localhost:8080/api/teacher/students', {
      headers: { 'Authorization': `Bearer ${authStore.token}` }
    })
    if (res.ok) {
      students.value = await res.json()
    }
  } finally {
    loading.value = false
  }
}

const handleAdd = async (e: Event) => {
  e.preventDefault()
  const res = await fetch('http://localhost:8080/api/teacher/students', {
    method: 'POST',
    headers: { 
      'Content-Type': 'application/json',
      'Authorization': `Bearer ${authStore.token}`
    },
    body: JSON.stringify(formData.value)
  })
  if (res.ok) {
    isAdding.value = false
    formData.value = { username: '', password: '', displayName: '' }
    fetchStudents()
  } else {
    const data = await res.json()
    alert(data.error || '添加失败')
  }
}

const triggerCsvUpload = () => {
  fileInput.value?.click()
}

const handleCsvUpload = async (e: Event) => {
  const target = e.target as HTMLInputElement
  const file = target.files?.[0]
  if (!file) return

  const text = await file.text()
  const lines = text.split('\n').filter(l => l.trim())
  const studentsList = lines.map(l => {
    const [username, displayName, password] = l.split(',').map(s => s.trim())
    return { username, displayName, password }
  }).filter(s => s.username && s.displayName && s.password)

  if (studentsList.length === 0) {
    alert('CSV 格式错误或为空。请提供包含账号,姓名,密码三列的 CSV 文件。')
    return
  }

  if (!confirm(`准备导入 ${studentsList.length} 名学生，确定吗？`)) return

  const res = await fetch('http://localhost:8080/api/teacher/students/batch', {
    method: 'POST',
    headers: { 
      'Content-Type': 'application/json',
      'Authorization': `Bearer ${authStore.token}`
    },
    body: JSON.stringify({ students: studentsList })
  })
  
  if (res.ok) {
    alert('导入成功')
    fetchStudents()
    isAdding.value = false
  } else {
    const data = await res.json()
    alert(data.error || '导入失败')
  }
  if (fileInput.value) fileInput.value.value = ''
}

const handleEdit = (student: Student) => {
  editingId.value = student.id
  editData.value = { displayName: student.displayName, password: '', isActive: student.isActive ?? true }
}

const handleSaveEdit = async (id: string) => {
  const res = await fetch(`http://localhost:8080/api/teacher/students/${id}`, {
    method: 'PUT',
    headers: { 
      'Content-Type': 'application/json',
      'Authorization': `Bearer ${authStore.token}`
    },
    body: JSON.stringify(editData.value)
  })
  if (res.ok) {
    editingId.value = null
    fetchStudents()
  } else {
    const data = await res.json()
    alert(data.error || '修改失败')
  }
}

const handleDelete = async (id: string) => {
  if (!confirm('警告：您即将删除该学生。这将同时硬删除其所有生图记录和历史对话！此操作不可恢复。确定要删除吗？')) return
  isDeleting.value = true
  try {
    const res = await fetch(`http://localhost:8080/api/teacher/students/${id}`, { 
      method: 'DELETE',
      headers: { 'Authorization': `Bearer ${authStore.token}` }
    })
    if (res.ok) {
      fetchStudents()
    } else {
      const data = await res.json()
      alert(data.error || '删除失败')
    }
  } finally {
    isDeleting.value = false
  }
}

onMounted(() => {
  fetchStudents()
})
</script>

<template>
  <div style="max-width: 1200px; margin: 0 auto;">
    <div style="display: flex; justify-content: space-between; align-items: center; margin-bottom: 1.5rem;">
      <h1 style="font-family: 'Cormorant Garamond', serif; font-size: 48px; margin: 0; color: var(--ink);">学生管理</h1>
      <button class="btn btn-primary" @click="isAdding = !isAdding">
        {{ isAdding ? '取消' : '添加学生' }}
      </button>
    </div>

    <div v-if="isAdding" class="glass-panel" style="padding: 1.5rem; margin-bottom: 2rem;">
      <div style="display: flex; justify-content: space-between; align-items: center; margin-bottom: 1rem;">
        <h2 style="font-size: 1.2rem; margin: 0;">添加新学生</h2>
        <div>
          <input type="file" accept=".csv" ref="fileInput" style="display: none;" @change="handleCsvUpload" />
          <button class="btn btn-secondary" @click="triggerCsvUpload">
            批量导入 (CSV)
          </button>
        </div>
      </div>
      <form @submit="handleAdd" style="display: flex; gap: 1rem; align-items: flex-end;">
        <div style="flex: 1;">
          <label style="display: block; margin-bottom: 0.5rem; font-size: 0.9rem; color: var(--muted);">学号/账号</label>
          <input required v-model="formData.username" style="width: 100%;" />
        </div>
        <div style="flex: 1;">
          <label style="display: block; margin-bottom: 0.5rem; font-size: 0.9rem; color: var(--muted);">姓名</label>
          <input required v-model="formData.displayName" style="width: 100%;" />
        </div>
        <div style="flex: 1;">
          <label style="display: block; margin-bottom: 0.5rem; font-size: 0.9rem; color: var(--muted);">密码</label>
          <input required type="password" v-model="formData.password" style="width: 100%;" />
        </div>
        <button type="submit" class="btn btn-primary" style="height: 42px;">保存单个</button>
      </form>
    </div>

    <div class="glass-panel">
      <div v-if="loading" style="padding: 2rem; text-align: center;">加载中...</div>
      <div v-else-if="students.length === 0" style="padding: 2rem; text-align: center; color: var(--muted);">暂无学生，请先添加</div>
      <table v-else style="width: 100%; border-collapse: collapse; text-align: left;">
        <thead>
          <tr style="border-bottom: 1px solid var(--hairline);">
            <th style="padding: 1rem; color: var(--muted); font-weight: 500;">账号</th>
            <th style="padding: 1rem; color: var(--muted); font-weight: 500;">姓名</th>
            <th style="padding: 1rem; color: var(--muted); font-weight: 500;">状态</th>
            <th style="padding: 1rem; color: var(--muted); font-weight: 500;">加入时间</th>
            <th style="padding: 1rem; color: var(--muted); font-weight: 500;">生成次数</th>
            <th style="padding: 1rem; color: var(--muted); font-weight: 500; text-align: right;">操作</th>
          </tr>
        </thead>
        <tbody>
          <tr v-for="student in students" :key="student.id" :style="{ borderBottom: '1px solid rgba(0,0,0,0.05)', background: editingId === student.id ? 'var(--surface-cream-strong)' : 'transparent' }">
            <td style="padding: 1rem;">{{ student.username }}</td>
            <td style="padding: 1rem;">
              <input v-if="editingId === student.id" v-model="editData.displayName" style="padding: 0.4rem; width: 120px;" />
              <span v-else>{{ student.displayName }}</span>
            </td>
            <td style="padding: 1rem;">
              <select v-if="editingId === student.id" v-model="editData.isActive" style="padding: 0.4rem;">
                <option :value="true">正常</option>
                <option :value="false">已停用</option>
              </select>
              <span v-else :style="{ padding: '4px 8px', borderRadius: '12px', fontSize: '12px', background: student.isActive !== false ? 'rgba(34, 197, 94, 0.1)' : 'rgba(239, 68, 68, 0.1)', color: student.isActive !== false ? '#15803d' : '#b91c1c' }">
                {{ student.isActive !== false ? '正常' : '已停用' }}
              </span>
            </td>
            <td style="padding: 1rem; color: var(--muted);">{{ new Date(student.createdAt).toLocaleDateString() }}</td>
            <td style="padding: 1rem;">{{ student._count?.generations || 0 }}</td>
            <td style="padding: 1rem; text-align: right;">
              <div v-if="editingId === student.id" style="display: flex; gap: 0.5rem; justify-content: flex-end; align-items: center;">
                <input type="password" placeholder="留空不改密码" v-model="editData.password" style="padding: 0.4rem; width: 120px; font-size: 0.8rem;" />
                <button class="btn btn-primary" style="padding: 0.4rem 0.8rem;" @click="handleSaveEdit(student.id)">保存</button>
                <button class="btn btn-secondary" style="padding: 0.4rem 0.8rem;" @click="editingId = null">取消</button>
              </div>
              <div v-else style="display: flex; gap: 0.5rem; justify-content: flex-end;">
                <button class="btn btn-secondary" style="padding: 0.4rem 0.8rem;" @click="handleEdit(student)">编辑</button>
                <button class="btn btn-secondary" style="padding: 0.4rem 0.8rem; color: var(--error);" @click="handleDelete(student.id)" :disabled="isDeleting">删除</button>
              </div>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</template>
